# Generated by Django 5.1.7 on 2025-04-06 06:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_contactmessage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='message',
            field=models.TextField(blank=True, default='', verbose_name='message'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Phone number must be 8-15 digits, optionally starting with +', regex='^\\+?[0-9]{8,15}$')], verbose_name='phone number'),
        ),
    ]
