# Generated by Django 5.1.7 on 2025-04-08 14:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_contactmessage_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='country',
            field=models.CharField(help_text='Your country of residence', max_length=100, verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='course',
            field=models.CharField(help_text="Course you're interested in", max_length=255, verbose_name='course interest'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='email',
            field=models.EmailField(help_text="We'll contact you at this email", max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='is_processed',
            field=models.BooleanField(default=False, help_text='Mark as processed when addressed', verbose_name='processed status'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='message',
            field=models.TextField(blank=True, default='', help_text='Additional details about your inquiry', verbose_name='message'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='name',
            field=models.CharField(help_text='Enter your full name', max_length=255, verbose_name='full name'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(help_text='Include country code if international', max_length=20, validators=[django.core.validators.RegexValidator(message='Phone number must be 8-15 digits, optionally starting with +', regex='^\\+?[0-9]{8,15}$')], verbose_name='phone number'),
        ),
        migrations.AddIndex(
            model_name='contactmessage',
            index=models.Index(fields=['email'], name='users_conta_email_94d804_idx'),
        ),
        migrations.AddIndex(
            model_name='contactmessage',
            index=models.Index(fields=['phone'], name='users_conta_phone_cf29e5_idx'),
        ),
        migrations.AddIndex(
            model_name='contactmessage',
            index=models.Index(fields=['submitted_at'], name='users_conta_submitt_bf644a_idx'),
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
